pre-commit:
  parallel: true
  commands:
    go-lint:
      run: staticcheck ./...
    go-modernize:
      run: |
        modernize ./...
    go-mod:
      run: go mod tidy -diff
    go-mod-verify:
      run: go mod verify > /dev/null
    go-fmt:
      run: go fmt ./...
    go-vet:
      run: go vet ./...
    typos:
      run: typos
